# Generated by Django 4.0.4 on 2022-05-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
