# Generated by Django 4.0.4 on 2022-05-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
