# Generated by Django 4.0.4 on 2022-05-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('shipped', models.DateField(blank=True)),
                ('shipping_address', models.CharField(max_length=255)),
                ('buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerid', to='user.user')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerid', to='user.user')),
            ],
        ),
    ]
