# Generated by Django 4.0.4 on 2022-05-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='city',
            field=models.CharField(default='Reykjavík', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='country',
            field=models.CharField(default='Iceland', max_length=255),
            preserve_default=False,
        ),
    ]
