# Generated by Django 4.0.4 on 2022-05-10 22:16

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_city_sale_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_name', models.CharField(max_length=255)),
                ('credit_card_number', creditcards.models.CardNumberField(max_length=16)),
                ('expiration_date', creditcards.models.CardExpiryField(default=None)),
                ('cvv', creditcards.models.SecurityCodeField(default=None, max_length=4)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
