# Generated by Django 4.0.4 on 2022-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='postal_code',
            field=models.CharField(default='113', max_length=255),
            preserve_default=False,
        ),
    ]
