# Generated by Django 4.0.4 on 2022-05-04 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_remove_user_email_remove_user_password_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
