# Generated by Django 4.0.4 on 2022-05-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth',
        ),
    ]
