# Generated by Django 4.0.4 on 2022-05-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/images/default_pic.jpg', null=True, upload_to=''),
        ),
    ]
