# Generated by Django 4.0.4 on 2022-05-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_user_id_alter_user_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth',
            new_name='id',
        ),
    ]
